name: "CI - On main/dev/release branches"
on:
  pull_request:
    branches:
      - dev
      - main
      - 'releases/**'
    paths-ignore:
      - '**/package.xml'

jobs:
  CI:
    uses: MOV-AI/.github/.github/workflows/ros-workflow.yml@debug/duarte
    with:
      deploy: 'false'
      ros_distro: '["noetic"]'
    secrets:
      auto_commit_user: ${{ secrets.RAISE_BOT_COMMIT_USER }}
      auto_commit_mail: ${{ secrets.RAISE_BOT_COMMIT_MAIL }}
      registry_user: ${{ secrets.PORTUS_APP_USER }}
      registry_password: ${{ secrets.PORTUS_APP_TOKEN }}
      nexus_publisher_user: ${{ secrets.NEXUS_PUBLISHER_USR }}
      nexus_publisher_password: ${{ secrets.NEXUS_PUBLISHER_PWD }}
      aws_sqs_rosdep_access_key: ${{ secrets.AWS_SQS_ROSDEP_ACCESS_KEY }}
      aws_sqs_rosdep_secret_access_key: ${{ secrets.AWS_SQS_ROSDEP_SECRET_ACCESS_KEY }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}

